### ISSUE TITLE
使用本地代理地址，aioxs的修改接口(put 204 no content)会一直是pending状态;use @vue/cli's proxy address, axios's edit api(put 204 no content) satus is alawys pending

### ISSUE THREAD

**Issue by flyinghigherair** [xianhc/apevolo-web#2]
如果将request.js中配置的baseURL直接修改为线上地址则正常（因之前无法请求，服务器后来开启了跨域）
if I modify request.js baseURL with real api address，it work good（The server turned on cross domain because it was unable to request before）

**Comment by xianhc** [comment]
@flyinghigherair 服务器部署的吗，可以多贴一些错误信息出来看看。服务器部署的方式各种千秋，代理问题需要错误信息分析

**Comment by xianhc** [comment]
后面我会整理出一份文档各种系统的部署方式参考

**Comment by xianhc** [comment]
204无响应就是跨域了，可以多贴一些错误信息参考一下，后面我整理一份部署的操作文档供大家参考

**Comment by xianhc** [comment]
@flyinghigherair 或许可以将编辑的接口返回204全部换成返回200尝试
